#dist: xenial
language: cpp
env:
    ###########################################################################
    # Configurations
    #
    # Each line in the "env" section represents a set of environment variables
    # passed to a build. Thus each line represents a different build
    # configuration.
    ###########################################################################

    # Check a subset of the matrix of:
    #   LLVM  : {3.8, 3.9, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0}
    #   SOLVERS : {Z3, STP, STP:Z3, metaSMT}
    #   STP_VERSION   : {2.3.3, master}
    #   METASMT_VERSION : {v4.rc1}
    #   METASMT_DEFAULT : {BTOR, CVC4, STP, YICES2, Z3}
    #   METASMT_BOOST_VERSION : {x.y.z} // e.g. 1.60.0, libboost-dev will be used if unspecified
    #   UCLIBC: {0, klee_uclibc_v1.0.0, klee_0_9_29} // Note ``0`` means disabled
    #   DISABLE_ASSERTIONS: {0, 1}
    #   ENABLE_OPTIMIZED: {0, 1}
    #   COVERAGE: {0, 1} // when set indicates that coverage data should be uploaded to the service
    #   USE_TCMALLOC: {0, 1}

    # Define default values - they are overwritten by each matrix entry if needed
    global:
    # Default configuration for all Travis-CI jobs. They are overriden by each job.
    - BASE_IMAGE=ubuntu:bionic-20200807
    - REPOSITORY=klee

    - COVERAGE=0
    - DISABLE_ASSERTIONS=0
    - ENABLE_DOXYGEN=0
    - ENABLE_OPTIMIZED=1
    - ENABLE_DEBUG=1
    - GTEST_VERSION=1.7.0
    - KLEE_RUNTIME_BUILD="Debug+Asserts"
    - LLVM_VERSION=11.0
    - METASMT_VERSION=qf_abv
    - MINISAT_VERSION="master"
    - REQUIRES_RTTI=0
    - SANITIZER_BUILD=
    - SOLVERS=STP:Z3
    - STP_VERSION=2.3.3
    - TCMALLOC_VERSION=2.7
    - UCLIBC_VERSION=klee_uclibc_v1.2
    - USE_TCMALLOC=1
    - USE_LIBCXX=1
    - Z3_VERSION=4.8.4

jobs:
    include:
    # Check supported LLVM versions
    - name: "LLVM 11"
      env: LLVM_VERSION=11.0


cache:
  ccache: true
  apt: true

before_script:
    # Ensure scripts have execute permissions
    - chmod +x scripts/build/build.sh scripts/build/run-tests.sh

script:
    # Build KLEE and run tests
    - if [[ "${BUILD_DOCKER}" != "1" && "$TRAVIS_OS_NAME" == "osx" ]]; then export BASE=/tmp && export PATH="/usr/local/opt/ccache/libexec:/usr/local/bin:$PATH"; scripts/build/build.sh klee --debug --install-system-deps; export DYLD_LIBRARY_PATH=="$(cd ${BASE}/metaSMT-*-deps/stp-git-basic/lib/ && pwd)"; scripts/build/run-tests.sh /tmp/klee_build* --debug; fi
    - if [[ "${BUILD_DOCKER}" != "1" && "$TRAVIS_OS_NAME" == "linux" ]]; then scripts/build/build.sh klee --docker --debug --push-docker-deps --create-final-image; fi
    - if [[ "${BUILD_DOCKER}" != "1" && "$COVERAGE" == "1" && "$TRAVIS_OS_NAME" == "linux" ]]; then scripts/build/run-tests.sh --coverage --upload-coverage --run-docker --debug; fi
    - if [[ "${BUILD_DOCKER}" != "1" && "$COVERAGE" == "0" && "$TRAVIS_OS_NAME" == "linux" ]]; then scripts/build/run-tests.sh --run-docker --debug; fi
    - if [[ "${BUILD_DOCKER}" -eq 1 ]]; then docker build .; fi
